language: ruby
rvm:
  - 2.0
  
install:
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable

before_script:
  - npm install -g writewell

script:
  - script/cibuild
 # - writewell -l script/list-of-files.txt
