# For Atom Feed
domain: services.github.com
author: GitHub, Inc.
email: services@github.com
title: On Demand Training

# standard jekyll configuration

baseurl: /on-demand
parentsite: https://services.github.com
permalink: /articles/:title/
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

collections:
  modules:
    output: true
  courses:
    output: true

include:
- _stylesheets
- _javascript
sass:
  sass_dir: assets/vendor/
  style: :compressed

# Custom site configuration
lang: en
